name: Actionlint

on: [push, pull_request]

jobs:
  actionlint:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install actionlint
      run: |
        curl -sSfL "https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash" | bash
        echo "$(pwd)/actionlint" >> "$GITHUB_PATH"

    - name: Run actionlint
      run: |
       ./actionlint --version
       for file in $(git ls-files ".github/workflows/*")
       do
         echo "./actionlint \"$file\""
         ./actionlint "$file"
       done